services:
  dq_postgres:
    image: postgres:latest
    container_name: dq_postgres
    restart: "no"
    environment:
      POSTGRES_USER: dquser
      POSTGRES_PASSWORD: dqpassword
      POSTGRES_DB: dataquality
    ports:
      - "5432:5432"
    volumes:
      - dq_postgres_data:/var/lib/postgresql

volumes:
  dq_postgres_data:


