services:
  dq_postgres_audit:
    image: postgres:latest
    container_name: dq_postgres_audit
    restart: "no"  # unless-stopped
    environment:
      POSTGRES_USER: dquser
      POSTGRES_PASSWORD: dqpassword
      POSTGRES_DB: dataquality
    ports:
      - "5432:5432"
    volumes:
      - dq_postgres_data1_4_2:/var/lib/postgresql

volumes:
  dq_postgres_data1_4_2:


