# Select a theme for your site
theme: jekyll-theme-minimal

# Site title and description
title: Data Quality for Software Engineers
logo: DQ_Book_Logo300.png
description: Open access Book about Data Quality for Software Engineers
show_downloads: true
google_analytics: G-78NWWZWFS4
