# Select a theme for your site
theme: jekyll-theme-minimal

# Site title and description
title: Data Quality for Software Engineers
logo: DQ_Book_Logo300.png
description: Official website for the open-source book "Data Quality for Software Engineers" from Roland and Richard Petrasch
show_downloads: true
google_analytics: G-78NWWZWFS4
